"""Change website to website_link 

Revision ID: 62f3a0894512
Revises: 0b846bd8588c
Create Date: 2021-05-11 20:37:40.557813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '62f3a0894512'
down_revision = '0b846bd8588c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('Artist', 'website')
    op.add_column('Venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('Venue', 'website')
    op.drop_column('Artist', 'genres')
    op.add_column('Artist', sa.Column('genres', postgresql.ARRAY(sa.String(length=120)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website_link')
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
